In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [5]:
np.array([1,2,5], dtype=complex) # or np.array([1,2,5], dtype='complex')

array([1.+0.j, 2.+0.j, 5.+0.j])

In [6]:
np.array([1,0,5],dtype=bool) # or np.array([1,0,5],dtype=bool)

array([ True, False,  True])

In [7]:
np.array([1,2,5], dtype=float) # or np.array([1,2,5], dtype=float)

array([1., 2., 5.])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
np.arange(1,16,2).reshape(4,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [14]:
np.random.random((3,4))

array([[0.36564891, 0.48371943, 0.06676885, 0.46902594],
       [0.16638672, 0.2295524 , 0.44582849, 0.55648546],
       [0.95809969, 0.31228548, 0.6895472 , 0.00981866]])

In [15]:
#linear space
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.linspace(1,20,10,dtype=complex)

array([ 1.        +0.j,  3.11111111+0.j,  5.22222222+0.j,  7.33333333+0.j,
        9.44444444+0.j, 11.55555556+0.j, 13.66666667+0.j, 15.77777778+0.j,
       17.88888889+0.j, 20.        +0.j])

In [18]:
np.identity(3,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [19]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [20]:
a1=np.array([1,2,3])
a2=np.array([[1,2,3],[4,5,6]])
a3=np.array([[[1,2],[3,4]],[[2,2],[3,4]]])
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [21]:
a4=np.array([1,2,4,5],dtype=np.int64)
print(a4.itemsize)
a2.itemsize

8


4

In [22]:
print(a1.dtype)
print(a2.dtype)
print(a4.dtype)

int32
int32
int64


In [23]:
#astype basically used to optimize the memory
a2.astype(np.int32)
print(a1.dtype)
a2.dtype

int32


dtype('int32')

In [24]:
a5= np.array([1,22,3])
#in collab the default size of int is int64 i.e 8 bytes but in jupyter notebook it is int32 i.e 4 bytes

In [25]:
#scalar operation
#arithematic
print(a2 ** 2)
a2/2

[[ 1  4  9]
 [16 25 36]]


array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [26]:
#relational 
a3<3

array([[[ True,  True],
        [False, False]],

       [[ True,  True],
        [False, False]]])

In [27]:
#vector operation
print(a1+a2)
print(a1*a2)
print(a1**a2)

[[2 4 6]
 [5 7 9]]
[[ 1  4  9]
 [ 4 10 18]]
[[  1   4  27]
 [  1  32 729]]


In [28]:
#aggregate operation
print(np.max(a3))
print(np.min(a3))
print(np.product(a3))
print(np.sum(a3))

4
1
1152
21


In [29]:
#axis 
#0->row 1->col
print(np.max(a3,axis=1))
print(np.min(a2,axis=1))
print("----------------")
print(np.max(a3,axis=0))
print(np.max(a2,axis=0))
print("----------------")
print(np.prod(a3,axis=1))

[[3 4]
 [3 4]]
[1 4]
----------------
[[2 2]
 [3 4]]
[4 5 6]
----------------
[[3 8]
 [6 8]]


In [30]:
b1=np.array([[12,13,14],[15,16,17],[18,19,20]])
b1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [31]:
print(np.max(b1,axis=1))
print(np.min(b1,axis=1))
print("----------------")
print(np.max(b1,axis=0))
print(np.max(b1,axis=0))
print("----------------")
print(np.prod(b1,axis=1))
print(np.sum(b1,axis=0))

[14 17 20]
[12 15 18]
----------------
[18 19 20]
[18 19 20]
----------------
[2184 4080 6840]
[45 48 51]


In [32]:
print(np.mean(b1,axis=1))
print(np.median(b1,axis=1))
print(np.var(b1,axis=1))
print(np.std(b1,axis=1))

[13. 16. 19.]
[13. 16. 19.]
[0.66666667 0.66666667 0.66666667]
[0.81649658 0.81649658 0.81649658]


In [33]:
b3=np.arange(6).reshape(2,3)
b2=np.arange(12).reshape(3,4)
print(b2)
print(b3)
print(np.dot(b1,b2))
print(np.dot(b3,b2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2]
 [3 4 5]]
[[164 203 242 281]
 [200 248 296 344]
 [236 293 350 407]]
[[20 23 26 29]
 [56 68 80 92]]


In [34]:
print(np.log(b1))
print(np.exp(b1))

[[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]]
[[1.62754791e+05 4.42413392e+05 1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08]]


In [35]:
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[27. 82. 26.]
 [19. 53. 15.]]
[[70. 92. 12.]
 [55. 93. 70.]]
[[26. 61. 94.]
 [35. 51. 51.]]


In [36]:
#ingdexing and slicing
a1=np.arange(8).reshape(2,2,2)
a1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
print(a1[0,1,1])
print(a1[1,1,1])
print(a1[1,0,1])
print(a1[1,0,0])
print(a1[1,1,0])

3
7
5
4
6


In [38]:
#for 2D
b1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [39]:
print(b1[1:,1:3])

[[16 17]
 [19 20]]


In [40]:
b2=np.arange(12).reshape(3,4)
b2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [42]:
b2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [43]:
b2[1,::3]

array([4, 7])

In [44]:
b2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [45]:
#for 3D
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [46]:
print(a3[::2])
print('-----------------------')
print(a3[:,1,:])
print('-----------------------')
print(a3[0,1,:])
print('-----------------------')
print(a3[1,:,1])
print('-----------------------')
print(a3[-1,1:,1:])
print('-----------------------')
print(a3[::2,0,::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-----------------------
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
-----------------------
[3 4 5]
-----------------------
[10 13 16]
-----------------------
[[22 23]
 [25 26]]
-----------------------
[[ 0  2]
 [18 20]]


In [47]:
#iteration
#for 1D array it will print as sequence
a1=np.arange(12)
for i in a1:
    print(i)
print('--------------')
#here it will print in matrix format
for i in a3:
    print(i)
print('--------------')
#so in order to display like sequence in 1D array we use nditer which will convert any dimension array to 1D and 
#then displays in sequence
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
--------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
--------------
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [48]:
#transpose
a4=np.arange(12).reshape(3,4)
print(a4)
print('--------------')
print("another syntax of transpose\n",a4.T)
print('--------------')
print(np.transpose(a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------
another syntax of transpose
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
--------------
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [49]:
#ravel : coverts any dimension array to 1D array without for loop
a3.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [50]:
#stacking horizontal and vertical
s1=np.arange(10).reshape(5,2)
s2=np.arange(11,21).reshape(5,2)
print(s1,"\n\n",s2)
print('-----------------')
print(np.hstack((s1,s2)))
print('-----------------')
print(np.vstack((s1,s2)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

 [[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
-----------------
[[ 0  1 11 12]
 [ 2  3 13 14]
 [ 4  5 15 16]
 [ 6  7 17 18]
 [ 8  9 19 20]]
-----------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [51]:
#splitting Horizontal and vertical splitting
s3=np.hstack((s1,s2))
s4=np.vstack((s1,s2))
print(s4)
print('------------------------------')
s5=np.hsplit(s3,2)
print(s5)
print('------------------------------')
#vsplit for this s3 won't happen bcz it has 3 rows and wouldn't divide 
s6=np.arange(12).reshape(4,3)
np.vsplit(s4,2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
------------------------------
[array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]]), array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])]
------------------------------


[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])]